r2981@harrypotter (orig r2980):  tom | 2008-09-25 18:53:13 +0100  libpng and jpeg libraries, just the direct source, then  ran configure, no other changes  r2982@harrypotter (orig r2981):  tom | 2008-09-25 19:00:26 +0100  cleaned up libpng and jpeg after distclean  r2983@harrypotter (orig r2982):  tom | 2008-09-25 19:21:36 +0100  - Updated app icon images away from "Jive" (based on Dean suggestion, just using the ones from SC).  - Added png, jpeg to macosx build  - Added initial SqueezePlay.app generation  r2985@harrypotter (orig r2984):  tom | 2008-09-25 21:02:12 +0100  got rid of my undeeded debug statements  r2986@harrypotter (orig r2985):  tom | 2008-09-25 21:43:37 +0100  copy .app bundle to the build dir  r2987@harrypotter (orig r2986):  awy | 2008-09-26 08:04:52 +0100  Implement pause-for-interval (using silence).  r2988@harrypotter (orig r2987):  awy | 2008-09-26 08:53:30 +0100  Don't send STMl after autostart.  r2989@harrypotter (orig r2988):  awy | 2008-09-26 10:35:15 +0100  Comment  r2991@harrypotter (orig r2990):  awy | 2008-09-26 10:56:58 +0100  Note exact sample at new-track start.  r2993@harrypotter (orig r2992):  titmuss | 2008-09-26 14:43:23 +0100  Bug: N/A  Description:  Include amixer, it's useful.
 r2995@harrypotter (orig r2994):  tom | 2008-09-26 15:18:16 +0100
 - Added initial SqueezePlay.app generation - need Makefile.in for build system which doesn't have autotools
 r2998@harrypotter (orig r2997):  tom | 2008-09-26 18:21:39 +0100
 uncommented to temporarily get rid of win32 error:
 2>c:\svn\7.3-write\jive\squeezeplay\src\squeezeplay\src\audio\decode\decode_portaudio.c(71) : error C2036: 'void *' : unknown size
 
 r2999@harrypotter (orig r2998):  tom | 2008-09-26 20:20:45 +0100
 commented out to temporarily get rid of windows build error
 r3000@harrypotter (orig r2999):  bklaas | 2008-09-26 20:28:02 +0100
 Bug: 9576
 Description: loadApplet() instead of callService() in SetupWelcomeMeta in an attempt to fix Factory Reset regression
 
 r3001@harrypotter (orig r3000):  bklaas | 2008-09-26 20:49:06 +0100
 Bug: 9576
 Description: revert ineffective change
 r3002@harrypotter (orig r3001):  tom | 2008-09-26 23:15:25 +0100
 for mac make dmg disk image for SqueezePlay
 r3003@harrypotter (orig r3002):  tom | 2008-09-26 23:52:25 +0100
 - disabled, becuase hangs build - for mac make dmg disk image for SqueezePlay
 r3004@harrypotter (orig r3003):  awy | 2008-09-27 18:53:09 +0100
 Fix port of add-slience.
 r3008@harrypotter (orig r3007):  awy | 2008-09-29 16:42:49 +0100
 Reduce number of int size coercion warnings.
 r3009@harrypotter (orig r3008):  tom | 2008-09-29 17:05:35 +0100
 moved AboutJive applet to squeezeplay level
 r3010@harrypotter (orig r3009):  tom | 2008-09-29 17:39:49 +0100
 First trial of adding svn:ignore property to generated non-versioned objects so that these generated objects don't show up for things like 'svn status'
 r3011@harrypotter (orig r3010):  bklaas | 2008-09-29 19:35:25 +0100
 Bug: 9576, 7873
 Description: setupShow was being used as a method name in two different applets, both of which needed to register that as a service.
 
 they have been split into setupShowSelectPlayer and setupShowSetupLanguage
 
 this checkin fixes Factory Reset, as well as fixed a few other typos to service manager calls
 
 r3012@harrypotter (orig r3011):  tom | 2008-09-29 19:41:20 +0100
 tomw ide config files
 r3013@harrypotter (orig r3012):  tom | 2008-09-29 20:33:15 +0100
 remove unneeded M
 r3014@harrypotter (orig r3013):  bklaas | 2008-09-29 21:01:36 +0100
 Bug: 9576
 Description: another few fixes later in the setup screens for service manager API. This should fix it from not being able to select a wireless region.
 r3015@harrypotter (orig r3014):  tom | 2008-09-29 21:17:35 +0100
 another attempt to make dmg image work, will try in build system	
 r3016@harrypotter (orig r3015):  tom | 2008-09-29 21:36:05 +0100
 Ignore rm failure
 r3018@harrypotter (orig r3017):  tom | 2008-09-29 22:50:25 +0100
 separated dmg target
 r3020@harrypotter (orig r3019):  tom | 2008-09-30 14:04:01 +0100
 reverted M change, M is meaningful, M is love...
 r3022@harrypotter (orig r3021):  tom | 2008-09-30 15:22:04 +0100
 svn:ignores
 r3023@harrypotter (orig r3022):  tom | 2008-09-30 15:27:28 +0100
 testing build server issues
 r3024@harrypotter (orig r3023):  awy | 2008-09-30 15:43:44 +0100
 Fix track-start for short tracks.
 User DSCO for normal and error end-of-stream, and STMf just for stream flush indications.
 r3025@harrypotter (orig r3024):  tom | 2008-09-30 15:46:34 +0100
 testing build server issues
 r3027@harrypotter (orig r3026):  tom | 2008-09-30 16:17:49 +0100
 removed build troubleshooting logging
 r3028@harrypotter (orig r3027):  tom | 2008-09-30 16:18:18 +0100
 svn:ignores
 r3029@harrypotter (orig r3028):  tom | 2008-09-30 20:20:22 +0100
 -replaced Makefile DATA primaries for lua static files with wildcard copies
 -removed 4 unused static files (3 png and a wav)
 r3030@harrypotter (orig r3029):  tom | 2008-09-30 20:27:10 +0100
 trying to clear up weird false svn copy history
 r3031@harrypotter (orig r3030):  tom | 2008-09-30 20:28:38 +0100
 trying to clear up weird false svn copy history
 r3032@harrypotter (orig r3031):  tom | 2008-09-30 20:40:16 +0100
 trying to clear up weird false svn copy history - missed jive Makefile.in
 r3033@harrypotter (orig r3032):  tom | 2008-09-30 21:06:54 +0100
 touching to try to get jive_73 build to see this file
 r3034@harrypotter (orig r3033):  tom | 2008-09-30 22:04:40 +0100
 removed win32 makefile requirement


git-svn-id: https://svn.slimdevices.com/repos/jive/7.4/trunk/squeezeos@3036 bbe22326-0783-4b3a-ac2b-7ab96b24c8d9